"""auto update

Revision ID: 61bb5a5e06db
Revises: 1c75cc13bc1d
Create Date: 2026-04-15 07:22:43.565686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bb5a5e06db'
down_revision: Union[str, Sequence[str], None] = '1c75cc13bc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('student_user_id', sa.String(), nullable=False),
    sa.Column('note_text', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instructor_notes_id'), 'instructor_notes', ['id'], unique=False)
    op.create_table('student_consent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('allow_tracking', sa.Boolean(), nullable=False),
    sa.Column('student_name', sa.String(), nullable=False),
    sa.Column('student_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_consent_id'), 'student_consent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_consent_id'), table_name='student_consent')
    op.drop_table('student_consent')
    op.drop_index(op.f('ix_instructor_notes_id'), table_name='instructor_notes')
    op.drop_table('instructor_notes')
    # ### end Alembic commands ###